---
name: Build and Push Application
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Auto-Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./build/git-update.sh -v major

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mapupp
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Send SMS Notification
      if: failure()  
      env:
       AWS_REGION: us-east-1
      run: |
        aws sns publish --topic-arn "arn:aws:sns:us-east-1:841012855588:mapupnotification" --message "Workflow failed!" --region $AWS_REGION

    - name: Send SMS Notification
      if: success()  
      env:
       AWS_REGION: us-east-1
      run: |
        aws sns publish --topic-arn "arn:aws:sns:us-east-1:841012855588:mapupnotification" --message "Workflow success!" --region $AWS_REGION        
